name: Build & Deploy

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm install
          npm run build

      - name: Zip output
        run: tar -czf dist.tar.gz dist

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to server
        run: |
          mkdir -p ~/.ssh
          # echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          # chmod 600 ~/.ssh/id_rsa
          sshpass -p ${{ secrets.SCP_PASSWORD }} scp -T -o StrictHostKeyChecking=no ./dist.tar.gz app@139.196.78.171:/home/app/mask-portal

      - name: Unzip package
        run: sshpass -p ${{ secrets.SCP_PASSWORD }} ssh -o StrictHostKeyChecking=no app@139.196.78.171 "rm -rf /home/app/mask-portal/dist | tar -xvf /home/app/mask-portal/dist.tar.gz | mv /home/app/mask-portal/dist.tar.gz  /home/app/mask-portal/history/dist_$(date +"%Y-%m-%d_%H-%M-%S").tar.gz"
